// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCfdnGvkTnsv9ZwjMcrnftIGiZb4UWnM4',
    appId: '1:773129520599:web:725ded45e9acac3e71f792',
    messagingSenderId: '773129520599',
    projectId: 'gallerieimageapp-87856',
    authDomain: 'gallerieimageapp-87856.firebaseapp.com',
    storageBucket: 'gallerieimageapp-87856.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYifW7aRFwADskKApPPw6DUAvAaMxpB24',
    appId: '1:773129520599:android:4496ce70310d66b071f792',
    messagingSenderId: '773129520599',
    projectId: 'gallerieimageapp-87856',
    storageBucket: 'gallerieimageapp-87856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8LZ_cHa_hcS5B1GeMKU6V9XneY3rjykw',
    appId: '1:773129520599:ios:781a85745e506b3a71f792',
    messagingSenderId: '773129520599',
    projectId: 'gallerieimageapp-87856',
    storageBucket: 'gallerieimageapp-87856.appspot.com',
    iosClientId: '773129520599-i5lvntc6c4ac81r5531s4r6vqi8dbq01.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallerieImageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8LZ_cHa_hcS5B1GeMKU6V9XneY3rjykw',
    appId: '1:773129520599:ios:781a85745e506b3a71f792',
    messagingSenderId: '773129520599',
    projectId: 'gallerieimageapp-87856',
    storageBucket: 'gallerieimageapp-87856.appspot.com',
    iosClientId: '773129520599-i5lvntc6c4ac81r5531s4r6vqi8dbq01.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallerieImageApp',
  );
}
